name = "crimson"
background = [
    20,
    10,
    12,
    240,
]
canvas = [
    14,
    6,
    8,
    240,
]
border = [
    190,
    40,
    50,
    120,
]
accent = [
    240,
    60,
    70,
    255,
]
header_text = [
    255,
    200,
    205,
    255,
]
local_player = [
    255,
    100,
    110,
    255,
]
impostor_line = [
    255,
    30,
    30,
    230,
]
tab_layout = "Vertical"
corner_rounding = 6.0
card_opacity = 240
font_scale = 1.0
show_radar_grid = false
tracer_thickness = 1.7999999523162842
crewmate = [
    220,
    180,
    180,
    255,
]
impostor = [
    255,
    30,
    30,
    255,
]
scientist = [
    100,
    200,
    255,
    255,
]
engineer = [
    255,
    140,
    50,
    255,
]
guardian_angel = [
    255,
    240,
    240,
    255,
]
shapeshifter = [
    255,
    30,
    40,
    255,
]
crewmate_ghost = [
    200,
    160,
    160,
    200,
]
impostor_ghost = [
    255,
    80,
    80,
    200,
]
phantom = [
    190,
    40,
    180,
    255,
]
tracker = [
    110,
    240,
    130,
    255,
]
noisemaker = [
    255,
    100,
    180,
    255,
]
detective = [
    120,
    150,
    240,
    255,
]
viper = [
    220,
    40,
    80,
    255,
]
judge = [
    255,
    180,
    40,
    255,
]
